import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'LearnHub - Learn something new',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="layout">
        <header className="site-header">
          <div className="container site-header-inner">
            <Link href="/" className="site-logo">
              <span className="site-logo-mark">L</span>
              <span>LearnHub</span>
            </Link>

            <form action="/search" method="get" className="header-search">
              <input
                type="search"
                name="q"
                id="header-search-q"
                className="input header-search-input"
                autoComplete="off"
                placeholder="Search courses..."
              />
              <button className="btn btn-primary btn-sm">Search</button>
            </form>

            <nav className="site-nav">
              <Link href="/" className="site-nav-link">
                Home
              </Link>
              <Link href="/courses" className="site-nav-link">
                Courses
              </Link>
              <Link href="/instructors" className="site-nav-link">
                Instructors
              </Link>
              <Link href="/register" className="site-nav-link">
                Register
              </Link>
            </nav>
          </div>
        </header>

        <main className="layout-main">{children}</main>

        <footer className="site-footer">
          <div className="container">
            <p className="site-footer-copy">Copyright &copy 2026</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
